### ISSUE TITLE
simplification and false positives

### ISSUE THREAD

**Issue by amir-arad** [wixplosives/typescript-type-utils#1]
Hi

Seems like the EQUAL can do with a little simplification. 
also, there are false positives (at least one I've found).
```ts
declare const bad: ExpectTrue<EQUAL< any[], number[]>>; // false positive
```
here's another approach, based on [this discussion](https://github.com/gcanti/typelevel-ts/issues/39).

```ts
type NEW_EQUAL<T, U> =
    (<G>() => G extends T ? 1 : 2) extends (<G>() => G extends U ? 1 : 2) ? true : false
declare const good : ExpectFalse<NEW_EQUAL<any[], number[] >>; // true negative
```
see [playground](http://www.typescriptlang.org/play/#src=%2F%2F%20----%20type-utils%0D%0Aexport%20type%20ExpectTrue%3CT%20extends%20true%3E%20%3D%20T%0D%0Aexport%20type%20ExpectFalse%3CT%20extends%20false%3E%20%3D%20T%0D%0A%0D%0Aexport%20type%20UnionToIntersection%3CU%3E%20%3D%0D%0A%20%20(U%20extends%20any%20%3F%20(k%3A%20U)%20%3D%3E%20void%20%3A%20never)%20extends%20((k%3A%20infer%20I)%20%3D%3E%20void)%20%3F%20I%20%3A%20never%0D%0A%0D%0Aexport%20type%20EXTENDS%3CVALUE%2C%20EXPECTED%3E%20%3D%20EXPECTED%20extends%20VALUE%20%3F%20true%20%3A%20false%0D%0A%0D%0Aexport%20type%20EQUAL%3CVALUE%20extends%20EXPECTED%2C%20EXPECTED%3E%20%3D%20NOT_EQUAL%3CVALUE%2C%20EXPECTED%3E%20extends%20false%20%3F%20true%20%3A%20false%0D%0A%0D%0Aexport%20type%20NOT_EQUAL_INTERNAL%3CVALUE%2C%20EXPECTED%3E%20%3D%20UnionToIntersection%3CVALUE%3E%20extends%20UnionToIntersection%3CEXPECTED%3E%20%3F%0D%0A%20%20%20%20UnionToIntersection%3CEXPECTED%3E%20extends%20UnionToIntersection%3CVALUE%3E%20%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20false%20%3A%20true%20%3A%20true%0D%0A%0D%0Aexport%20type%20NOT_EQUAL%3CVALUE%2C%20EXPECTED%3E%20%3D%20true%20extends%20NOT_EQUAL_INTERNAL%3CVALUE%2C%20EXPECTED%3E%20%3F%20true%20%3A%20false%0D%0A%2F%2F%20----%0D%0A%0D%0A%2F%2F%20----%20candidate%0D%0Atype%20NEW_EQUAL%3CT%2C%20U%3E%20%3D%0D%0A%20%20%20%20(%3CG%3E()%20%3D%3E%20G%20extends%20T%20%3F%201%20%3A%202)%20extends%20(%3CG%3E()%20%3D%3E%20G%20extends%20U%20%3F%201%20%3A%202)%20%3F%20true%20%3A%20false%0D%0A%2F%2F%20----%0D%0A%0D%0A%0D%0A%2F%2F%20----%20test%0D%0Adeclare%20let%20a%3A%20any%5B%5D%0D%0Adeclare%20let%20b%3A%20number%5B%5D%0D%0A%0D%0Adeclare%20const%20bad%3A%20ExpectTrue%3CEQUAL%3Ctypeof%20a%2C%20typeof%20b%3E%3E%3B%20%2F%2F%20false%20positive%20%0D%0A%0D%0Adeclare%20const%20good%20%3A%20ExpectFalse%3CNEW_EQUAL%20%3C%20typeof%20a%2C%20typeof%20b%20%3E%3E%3B%20%2F%2F%20true%20negative%0D%0A%2F%2F%20---)

**Comment by nadavwix** [comment]
@amir-arad this code causes false positive in existing tests

**Comment by amir-arad** [comment]
@nadavwix well it's been 5 months since I made that suggestion... I assume the code changed.
